const DATA = {
  Restoran: {
    color: "#e8c872",
    words: [
      {
        kanji: "いらっしゃいませ",
        romaji: "Irasshaimase",
        arti: "Selamat datang",
      },
      { kanji: "注文", romaji: "Chūmon", arti: "Pesanan / Order" },
      { kanji: "メニュー", romaji: "Menyū", arti: "Menu" },
      { kanji: "お冷", romaji: "Ohiya", arti: "Air minum gratis" },
      { kanji: "お勘定", romaji: "Okanjō", arti: "Tagihan / Bil" },
      { kanji: "領収書", romaji: "Ryōshūsho", arti: "Kwitansi / Struk" },
      { kanji: "取り皿", romaji: "Torizara", arti: "Piring kecil" },
      { kanji: "箸", romaji: "Hashi", arti: "Sumpit" },
      { kanji: "スプーン", romaji: "Supūn", arti: "Sendok" },
      { kanji: "フォーク", romaji: "Fōku", arti: "Garpu" },
      { kanji: "コップ", romaji: "Koppu", arti: "Gelas" },
      { kanji: "予約", romaji: "Yoyaku", arti: "Reservasi / Pesan tempat" },
      { kanji: "満席", romaji: "Manseki", arti: "Kursi penuh" },
      { kanji: "禁煙席", romaji: "Kin'enseki", arti: "Kursi dilarang merokok" },
      { kanji: "喫煙席", romaji: "Kitsuenseki", arti: "Kursi boleh merokok" },
      { kanji: "厨房", romaji: "Chūbō", arti: "Dapur" },
      { kanji: "調理場", romaji: "Chōriba", arti: "Tempat memasak" },
      { kanji: "皿洗い", romaji: "Saraarai", arti: "Cuci piring" },
      { kanji: "接客", romaji: "Sekkyaku", arti: "Melayani pelanggan" },
      { kanji: "片付け", romaji: "Katazuke", arti: "Membereskan" },
      { kanji: "掃除", romaji: "Sōji", arti: "Bersih-bersih" },
      { kanji: "開店", romaji: "Kaiten", arti: "Toko buka" },
      { kanji: "閉店", romaji: "Heiten", arti: "Toko tutup" },
      { kanji: "看板", romaji: "Kanban", arti: "Papan nama / menu" },
      {
        kanji: "本日のおすすめ",
        romaji: "Honjitsu no osusume",
        arti: "Rekomendasi hari ini",
      },
      {
        kanji: "持ち帰り",
        romaji: "Mochikaeri",
        arti: "Bawa pulang / Take away",
      },
      { kanji: "生ビール", romaji: "Namabīru", arti: "Bir draf" },
      {
        kanji: "ソフトドリンク",
        romaji: "Sofuto dorinku",
        arti: "Minuman ringan",
      },
      { kanji: "おかわり", romaji: "Okawari", arti: "Tambah lagi (porsi)" },
      {
        kanji: "食べ放題",
        romaji: "Tabehōdai",
        arti: "Makan sepuasnya (Buffet)",
      },
      { kanji: "飲み放題", romaji: "Nomihōdai", arti: "Minum sepuasnya" },
      { kanji: "定食", romaji: "Teishoku", arti: "Paket makanan" },
      { kanji: "材料", romaji: "Zairyō", arti: "Bahan-bahan" },
      { kanji: "賞味期限", romaji: "Shōmi kigen", arti: "Tanggal kedaluwarsa" },
      { kanji: "冷蔵庫", romaji: "Reizōko", arti: "Kulkas" },
      { kanji: "冷凍庫", romaji: "Reitōko", arti: "Freezer" },
      { kanji: "手洗い", romaji: "Tearai", arti: "Cuci tangan" },
      { kanji: "消毒", romaji: "Shōdoku", arti: "Disinfektan / Steril" },
      { kanji: "制服", romaji: "Seifuku", arti: "Seragam" },
      { kanji: "笑顔", romaji: "Egao", arti: "Senyuman" },
      { kanji: "おしぼり", romaji: "Oshibori", arti: "Handuk basah" },
      { kanji: "会計", romaji: "Kaikei", arti: "Kasir / Pembayaran" },
      { kanji: "現金", romaji: "Genkin", arti: "Uang tunai" },
      {
        kanji: "クレジットカード",
        romaji: "Kurejitto kādo",
        arti: "Kartu kredit",
      },
      { kanji: "お釣り", romaji: "Otsuri", arti: "Uang kembalian" },
      { kanji: "レシート", romaji: "Reshīto", arti: "Struk" },
      { kanji: "お客様", romaji: "Okyakusama", arti: "Tamu / Pelanggan" },
      { kanji: "灰皿", romaji: "Haizara", arti: "Asbak" },
      { kanji: "デザート", romaji: "Dezāto", arti: "Makanan penutup" },
      {
        kanji: "少々お待ちください",
        romaji: "Shōshō omachi kudasai",
        arti: "Mohon tunggu sebentar",
      },
      {
        kanji: "お待たせいたしました",
        romaji: "Omatase itashimashita",
        arti: "Maaf membuat Anda menunggu",
      },
      {
        kanji: "かしこまりました",
        romaji: "Kashikomarimashita",
        arti: "Baik, saya mengerti",
      },
      {
        kanji: "ごゆっくりどうぞ",
        romaji: "Goyukkuri dōzo",
        arti: "Silakan dinikmati",
      },
      { kanji: "グラス", romaji: "Gurasu", arti: "Gelas kaca" },
      { kanji: "ストロー", romaji: "Sutorō", arti: "Sedotan" },
      { kanji: "氷", romaji: "Kōri", arti: "Es batu" },
      {
        kanji: "取り分ける",
        romaji: "Toriwakeru",
        arti: "Membagikan ke piring kecil",
      },
      { kanji: "アレルギー", romaji: "Arerugī", arti: "Alergi" },
      {
        kanji: "注文を取る",
        romaji: "Chūmon o toru",
        arti: "Mengambil pesanan",
      },
      { kanji: "おすすめ", romaji: "Osusume", arti: "Rekomendasi" },
    ],
  },
  Hotel: {
    color: "#5ecf8a",
    words: [
      { kanji: "チェックイン", romaji: "Chekku in", arti: "Check-in" },
      { kanji: "チェックアウト", romaji: "Chekku auto", arti: "Check-out" },
      { kanji: "予約", romaji: "Yoyaku", arti: "Reservasi" },
      { kanji: "フロント", romaji: "Furonto", arti: "Resepsionis" },
      { kanji: "鍵", romaji: "Kagi", arti: "Kunci" },
      { kanji: "カードキー", romaji: "Kādo kī", arti: "Kartu kunci" },
      { kanji: "エレベーター", romaji: "Erebētā", arti: "Lift" },
      { kanji: "非常口", romaji: "Hijōguchi", arti: "Pintu darurat" },
      { kanji: "階段", romaji: "Kaidan", arti: "Tangga" },
      { kanji: "ロビー", romaji: "Robī", arti: "Lobi" },
      { kanji: "客室", romaji: "Kyakushitsu", arti: "Kamar tamu" },
      {
        kanji: "シングルルーム",
        romaji: "Shinguru rūmu",
        arti: "Kamar satu orang",
      },
      { kanji: "ツインルーム", romaji: "Tsuin rūmu", arti: "Kamar dua orang" },
      { kanji: "朝食券", romaji: "Chōshokuken", arti: "Kupon sarapan" },
      { kanji: "バイキング", romaji: "Baikingu", arti: "Prasmanan / Buffet" },
      { kanji: "荷物", romaji: "Nimotsu", arti: "Barang bawaan" },
      { kanji: "預かり", romaji: "Azukari", arti: "Penitipan" },
      { kanji: "貴重品", romaji: "Kichōhin", arti: "Barang berharga" },
      { kanji: "金庫", romaji: "Kinko", arti: "Brankas / Safe box" },
      { kanji: "タオル", romaji: "Taoru", arti: "Handuk" },
      { kanji: "バスタオル", romaji: "Basutaoru", arti: "Handuk mandi" },
      { kanji: "歯ブラシ", romaji: "Haburashi", arti: "Sikat gigi" },
      { kanji: "石鹸", romaji: "Sekken", arti: "Sabun" },
      { kanji: "シャンプー", romaji: "Shanpū", arti: "Sampo" },
      { kanji: "ドライヤー", romaji: "Doraiyā", arti: "Pengering rambut" },
      { kanji: "エアコン", romaji: "Eakon", arti: "AC" },
      { kanji: "Wi-Fi", romaji: "Waifai", arti: "Wi-Fi" },
      { kanji: "パスワード", romaji: "Pasuwādo", arti: "Kata sandi" },
      {
        kanji: "モーニングコール",
        romaji: "Mōningu kōru",
        arti: "Layanan bangun pagi",
      },
      { kanji: "ルームサービス", romaji: "Rūmu sābisu", arti: "Layanan kamar" },
      {
        kanji: "禁煙室",
        romaji: "Kin'enshitsu",
        arti: "Kamar dilarang merokok",
      },
      { kanji: "喫煙室", romaji: "Kitsuenshitsu", arti: "Kamar boleh merokok" },
      { kanji: "駐車場", romaji: "Chūshajō", arti: "Tempat parkir" },
      { kanji: "送迎バス", romaji: "Sōgei basu", arti: "Bus antar-jemput" },
      { kanji: "お土産", romaji: "Omiyage", arti: "Oleh-oleh" },
      { kanji: "周辺案内", romaji: "Shūhen annai", arti: "Informasi sekitar" },
      { kanji: "清掃", romaji: "Seisō", arti: "Pembersihan" },
      { kanji: "連泊", romaji: "Renpaku", arti: "Menginap terus-menerus" },
      { kanji: "満室", romaji: "Manshitsu", arti: "Kamar penuh" },
      { kanji: "キャンセル", romaji: "Kyanseru", arti: "Pembatalan" },
      { kanji: "宿泊", romaji: "Shukuhaku", arti: "Menginap" },
      {
        kanji: "クローク",
        romaji: "Kurōku",
        arti: "Penitipan barang (Cloakroom)",
      },
      { kanji: "ベルボーイ", romaji: "Berubōi", arti: "Bellboy" },
      { kanji: "ドアマン", romaji: "Doaman", arti: "Doorman" },
      { kanji: "スイートルーム", romaji: "Suīto rūmu", arti: "Kamar suite" },
      { kanji: "ダブルルーム", romaji: "Daburu rūmu", arti: "Kamar double" },
      { kanji: "温泉", romaji: "Onsen", arti: "Pemandian air panas" },
      { kanji: "大浴場", romaji: "Daiyokujō", arti: "Pemandian umum besar" },
      { kanji: "非常ベル", romaji: "Hijō beru", arti: "Bel darurat" },
      { kanji: "ルームキー", romaji: "Rūmu kī", arti: "Kunci kamar" },
      {
        kanji: "コインランドリー",
        romaji: "Koin randorī",
        arti: "Laundry koin",
      },
      { kanji: "アイロン", romaji: "Airon", arti: "Setrika" },
      { kanji: "加湿器", romaji: "Kashitsuki", arti: "Pelembap udara" },
      { kanji: "毛布", romaji: "Mōfu", arti: "Selimut" },
      { kanji: "枕", romaji: "Makura", arti: "Bantal" },
      { kanji: "灰皿", romaji: "Haizara", arti: "Asbak" },
      {
        kanji: "フロントデスク",
        romaji: "Furonto desuku",
        arti: "Meja resepsionis",
      },
      {
        kanji: "荷物をお持ちします",
        romaji: "Nimotsu o omochi shimasu",
        arti: "Membawakan barang bawaan",
      },
      {
        kanji: "ごゆっくり",
        romaji: "Goyukkuri",
        arti: "Silakan menikmati waktu",
      },
      { kanji: "手続き", romaji: "Tetsuzuki", arti: "Prosedur / Proses" },
    ],
  },
  Konstruksi: {
    color: "#f0a070",
    words: [
      {
        kanji: "安全第一",
        romaji: "Anzen daiichi",
        arti: "Utamakan keselamatan",
      },
      { kanji: "ヘルメット", romaji: "Herumetto", arti: "Helm keselamatan" },
      { kanji: "安全靴", romaji: "Anzengutsu", arti: "Sepatu keselamatan" },
      { kanji: "手袋", romaji: "Tebukuro", arti: "Sarung tangan" },
      { kanji: "軍手", romaji: "Guntei", arti: "Sarung tangan kain" },
      { kanji: "道具", romaji: "Dōgu", arti: "Alat-alat / Perkakas" },
      { kanji: "機械", romaji: "Kikai", arti: "Mesin" },
      { kanji: "現場", romaji: "Genba", arti: "Lokasi kerja" },
      { kanji: "作業員", romaji: "Sagyōin", arti: "Pekerja" },
      { kanji: "足場", romaji: "Ashiba", arti: "Steger / Scaffolding" },
      { kanji: "階段", romaji: "Kaidan", arti: "Tangga" },
      { kanji: "はしご", romaji: "Hashigo", arti: "Tangga lipat" },
      { kanji: "高い所", romaji: "Takai tokoro", arti: "Tempat tinggi" },
      { kanji: "注意", romaji: "Chūi", arti: "Perhatian / Hati-hati" },
      { kanji: "危険", romaji: "Kiken", arti: "Bahaya" },
      { kanji: "立入禁止", romaji: "Tachiiri kinshi", arti: "Dilarang masuk" },
      { kanji: "整理整頓", romaji: "Seiri seiton", arti: "Rapi dan teratur" },
      { kanji: "清掃", romaji: "Seisō", arti: "Pembersihan" },
      { kanji: "ゴミ", romaji: "Gomi", arti: "Sampah" },
      { kanji: "運ぶ", romaji: "Hakobu", arti: "Membawa / Mengangkut" },
      { kanji: "材料", romaji: "Zairyō", arti: "Bahan bangunan" },
      { kanji: "図面", romaji: "Zumen", arti: "Gambar kerja / Denah" },
      { kanji: "測る", romaji: "Hakaru", arti: "Mengukur" },
      { kanji: "切る", romaji: "Kiru", arti: "Memotong" },
      { kanji: "穴を掘る", romaji: "Ana o horu", arti: "Menggali lubang" },
      { kanji: "コンクリート", romaji: "Konkurīto", arti: "Beton" },
      { kanji: "鉄筋", romaji: "Tekkin", arti: "Besi beton" },
      { kanji: "溶接", romaji: "Yōsetsu", arti: "Las" },
      { kanji: "ペンキ塗り", romaji: "Penki nuri", arti: "Mengecat" },
      { kanji: "電気工事", romaji: "Denki kōji", arti: "Pekerjaan listrik" },
      { kanji: "水道", romaji: "Suidō", arti: "Saluran air" },
      { kanji: "騒音", romaji: "Sōon", arti: "Suara bising" },
      { kanji: "埃", romaji: "Hokori", arti: "Debu" },
      { kanji: "マスク", romaji: "Masuku", arti: "Masker" },
      { kanji: "熱中症", romaji: "Netchūshō", arti: "Heatstroke (kepanasan)" },
      { kanji: "休憩", romaji: "Kyūkei", arti: "Istirahat" },
      { kanji: "水分補給", romaji: "Suibun hokyū", arti: "Minum air" },
      { kanji: "集合", romaji: "Shūgō", arti: "Kumpul" },
      { kanji: "報告", romaji: "Hōkoku", arti: "Laporan" },
      { kanji: "終了", romaji: "Shūryō", arti: "Selesai" },
      { kanji: "安全帯", romaji: "Anzentai", arti: "Sabuk pengaman" },
      {
        kanji: "危険予知",
        romaji: "Kiken yochi",
        arti: "Prediksi bahaya (KY)",
      },
      {
        kanji: "指差呼称",
        romaji: "Yubisashi koshō",
        arti: "Tunjuk dan sebut",
      },
      { kanji: "トラック", romaji: "Torakku", arti: "Truk" },
      { kanji: "クレーン", romaji: "Kurēn", arti: "Derek (Crane)" },
      { kanji: "フォークリフト", romaji: "Fōkurifuto", arti: "Forklift" },
      { kanji: "ダンプカー", romaji: "Danpukā", arti: "Dump truck" },
      { kanji: "ショベルカー", romaji: "Shoberukā", arti: "Ekskavator" },
      { kanji: "セメント", romaji: "Semento", arti: "Semen" },
      { kanji: "砂", romaji: "Suna", arti: "Pasir" },
      { kanji: "砂利", romaji: "Jari", arti: "Kerikil" },
      { kanji: "ペンチ", romaji: "Penchi", arti: "Tang" },
      { kanji: "ドライバー", romaji: "Doraibā", arti: "Obeng" },
      { kanji: "ハンマー", romaji: "Hanmā", arti: "Palu" },
      { kanji: "釘", romaji: "Kugi", arti: "Paku" },
      { kanji: "ノコギリ", romaji: "Nokogiri", arti: "Gergaji" },
      { kanji: "巻尺", romaji: "Makijaku", arti: "Meteran" },
      { kanji: "測量", romaji: "Sokuryō", arti: "Pengukuran" },
      { kanji: "現場監督", romaji: "Genba kantoku", arti: "Mandor lapangan" },
      { kanji: "作業服", romaji: "Sagyōfuku", arti: "Pakaian kerja" },
    ],
  },
  Pertanian: {
    color: "#70c9a0",
    words: [
      { kanji: "畑", romaji: "Hatake", arti: "Ladang" },
      { kanji: "田んぼ", romaji: "Tanbo", arti: "Sawah" },
      { kanji: "農家", romaji: "Nōka", arti: "Petani" },
      { kanji: "野菜", romaji: "Yasai", arti: "Sayuran" },
      { kanji: "果物", romaji: "Kudamono", arti: "Buah-buahan" },
      { kanji: "種", romaji: "Tane", arti: "Biji / Benih" },
      { kanji: "苗", romaji: "Nae", arti: "Bibit tanaman" },
      { kanji: "植える", romaji: "Ueru", arti: "Menanam" },
      { kanji: "収穫", romaji: "Shūkaku", arti: "Panen" },
      { kanji: "肥料", romaji: "Hiryō", arti: "Pupuk" },
      { kanji: "農薬", romaji: "Nōyaku", arti: "Obat hama / Pestisida" },
      { kanji: "虫", romaji: "Mushi", arti: "Serangga / Hama" },
      { kanji: "草取り", romaji: "Kusatori", arti: "Mencabut rumput" },
      { kanji: "水やり", romaji: "Mizuyari", arti: "Menyiram air" },
      { kanji: "土", romaji: "Tsuchi", arti: "Tanah" },
      { kanji: "耕す", romaji: "Tagayasu", arti: "Membajak tanah" },
      { kanji: "トラクター", romaji: "Torakutā", arti: "Traktor" },
      {
        kanji: "ビニールハウス",
        romaji: "Binīru hausu",
        arti: "Rumah plastik / Greenhouse",
      },
      { kanji: "気温", romaji: "Kion", arti: "Suhu udara" },
      { kanji: "天気予報", romaji: "Tenki yohō", arti: "Ramalan cuaca" },
      { kanji: "太陽", romaji: "Taiyō", arti: "Matahari" },
      { kanji: "雨", romaji: "Ame", arti: "Hujan" },
      { kanji: "風", romaji: "Kaze", arti: "Angin" },
      { kanji: "育てる", romaji: "Sodateru", arti: "Merawat / Membesarkan" },
      { kanji: "大きさ", romaji: "Ōkisa", arti: "Ukuran" },
      { kanji: "重さ", romaji: "Omosa", arti: "Berat" },
      { kanji: "箱詰め", romaji: "Hakozume", arti: "Memasukkan ke kotak" },
      { kanji: "出荷", romaji: "Shukka", arti: "Pengiriman barang" },
      { kanji: "新鮮", romaji: "Shinsen", arti: "Segar" },
      { kanji: "牛", romaji: "Ushi", arti: "Sapi" },
      { kanji: "豚", romaji: "Buta", arti: "Babi" },
      { kanji: "鶏", romaji: "Niwa-tori", arti: "Ayam" },
      { kanji: "卵", romaji: "Tamago", arti: "Telur" },
      { kanji: "餌", romaji: "Esa", arti: "Pakan hewan" },
      { kanji: "掃除", romaji: "Sōji", arti: "Pembersihan" },
      { kanji: "長靴", romaji: "Nagagutsu", arti: "Sepatu boot" },
      { kanji: "帽子", romaji: "Bōshi", arti: "Topi" },
      { kanji: "朝早い", romaji: "Asa hayai", arti: "Pagi-pagi sekali" },
      { kanji: "重労働", romaji: "Jūrōdō", arti: "Kerja berat" },
      { kanji: "協力", romaji: "Kyōryoku", arti: "Kerja sama" },
      { kanji: "田植え", romaji: "Taue", arti: "Menanam padi" },
      { kanji: "稲刈り", romaji: "Inekari", arti: "Memanen padi" },
      { kanji: "お米", romaji: "Okome", arti: "Beras" },
      { kanji: "トマト", romaji: "Tomato", arti: "Tomat" },
      { kanji: "キャベツ", romaji: "Kyabetsu", arti: "Kubis" },
      { kanji: "大根", romaji: "Daikon", arti: "Lobak" },
      { kanji: "じゃがいも", romaji: "Jagaimo", arti: "Kentang" },
      { kanji: "りんご", romaji: "Ringo", arti: "Apel" },
      { kanji: "みかん", romaji: "Mikan", arti: "Jeruk" },
      { kanji: "ぶどう", romaji: "Budō", arti: "Anggur" },
      { kanji: "雑草", romaji: "Zassō", arti: "Rumput liar" },
      { kanji: "害虫", romaji: "Gaichū", arti: "Hama serangga" },
      { kanji: "消毒", romaji: "Shōdoku", arti: "Penyemprotan obat" },
      { kanji: "肥料をやる", romaji: "Hiryō o yaru", arti: "Memberi pupuk" },
      { kanji: "軽トラ", romaji: "Keitora", arti: "Truk pikap kecil" },
      { kanji: "倉庫", romaji: "Sōko", arti: "Gudang" },
      {
        kanji: "直売所",
        romaji: "Chokubaisho",
        arti: "Tempat penjualan langsung",
      },
      { kanji: "農業機械", romaji: "Nōgyō kikai", arti: "Mesin pertanian" },
      { kanji: "日焼け", romaji: "Hiyake", arti: "Terbakar sinar matahari" },
      { kanji: "雨具", romaji: "Amagu", arti: "Jas hujan" },
    ],
  },
  "Pengelolaan Makanan": {
    color: "#f07878",
    words: [
      {
        kanji: "正しい",
        romaji: "Tadashii",
        arti: "yang benar",
      },
      {
        kanji: "間違っている",
        romaji: "Machigatteiru",
        arti: "yang salah",
      },
      {
        kanji: "方法",
        romaji: "Houhou",
        arti: "cara",
      },
      {
        kanji: "選びます",
        romaji: "Erabimasu",
        arti: "memilih",
      },
      {
        kanji: "食品安全",
        romaji: "Shokuhin Anzen",
        arti: "Keamanan Pangan",
      },
      {
        kanji: "品質",
        romaji: "Hinshitsu",
        arti: "Kualitas",
      },
      {
        kanji: "管理",
        romaji: "Kanri",
        arti: "Manajemen",
      },
      {
        kanji: "基本的な",
        romaji: "Kihonteki na",
        arti: "Dasar",
      },
      {
        kanji: "知識",
        romaji: "Chishiki",
        arti: "Pengetahuan",
      },
      {
        kanji: "大切",
        romaji: "Taisetsu",
        arti: "Penting",
      },
      {
        kanji: "食品",
        romaji: "Shokuhin",
        arti: "Makanan",
      },
      {
        kanji: "提供する",
        romaji: "Teikyou suru",
        arti: "Menawarkan",
      },
      {
        kanji: "全体像",
        romaji: "Zentaizou",
        arti: "Gambar Keseluruhan",
      },
      {
        kanji: "食中毒",
        romaji: "Shokuchuudoku",
        arti: "Keracunan Makanan",
      },
      {
        kanji: "防止",
        romaji: "Boushi",
        arti: "Pencegahan",
      },
      {
        kanji: "原則",
        romaji: "Gensoku",
        arti: "Prinsip",
      },
      {
        kanji: "関する",
        romaji: "Kansuru",
        arti: "Berhubungan dengan",
      },
      {
        kanji: "基礎知識",
        romaji: "Kiso Chishiki",
        arti: "Pengetahuan Dasar",
      },
      {
        kanji: "起こす",
        romaji: "Okosu",
        arti: "Bangun/Menimbulkan",
      },
      {
        kanji: "微生物",
        romaji: "Biseibutsu",
        arti: "Mikroorganisme",
      },
      {
        kanji: "増殖する",
        romaji: "Zoushoku suru",
        arti: "Berkembang biak",
      },
      {
        kanji: "要素",
        romaji: "Youso",
        arti: "Elemen",
      },
      {
        kanji: "温度",
        romaji: "Ondo",
        arti: "Suhu",
      },
      {
        kanji: "水分",
        romaji: "Suibun",
        arti: "Kelembapan",
      },
      {
        kanji: "栄誉分",
        romaji: "Eiyoubun",
        arti: "Nutrisi",
      },
      {
        kanji: "関係",
        romaji: "Kankei",
        arti: "Hubungan",
      },
      {
        kanji: "カビ",
        romaji: "Kabi",
        arti: "Jamur",
      },
      {
        kanji: "問題",
        romaji: "Mondai",
        arti: "Masalah",
      },
      {
        kanji: "製造",
        romaji: "Seizou",
        arti: "Manufaktur",
      },
      {
        kanji: "安心",
        romaji: "Anshin",
        arti: "Nyaman/Lega",
      },
      {
        kanji: "消費者",
        romaji: "Shouhisha",
        arti: "Konsumen",
      },
      {
        kanji: "不安",
        romaji: "Fuan",
        arti: "Cemas",
      },
      {
        kanji: "不信感",
        romaji: "Fushinkan",
        arti: "ketidakpercayaan",
      },
      {
        kanji: "高めます",
        romaji: "Takamemasu",
        arti: "meningkat",
      },
      {
        kanji: "結果",
        romaji: "Kekka",
        arti: "hasil",
      },
      {
        kanji: "影響",
        romaji: "Eikyou",
        arti: "efek / dampak",
      },
      {
        kanji: "売れなくなる",
        romaji: "Urenaku naru",
        arti: "tidak terjual/ tidak laku",
      },
      {
        kanji: "会社の信用",
        romaji: "Kaisha no Shinyou",
        arti: "kepercayaan perusahaan",
      },
      {
        kanji: "職場",
        romaji: "Shokuba",
        arti: "tempat kerja",
      },
      {
        kanji: "原材料",
        romaji: "Genzairyou",
        arti: "Bahan Baku",
      },
      {
        kanji: "製造環境",
        romaji: "Seizou Kankyou",
        arti: "Lingkungan Manufaktur",
      },
      {
        kanji: "衛生",
        romaji: "Eisei",
        arti: "Kebersihan/Higienis",
      },
      {
        kanji: "取り扱い",
        romaji: "Toriatsukai",
        arti: "Penanganan",
      },
      {
        kanji: "条件",
        romaji: "Jouken",
        arti: "Syarat",
      },
      {
        kanji: "重要な",
        romaji: "Juu You na",
        arti: "Perlu",
      },
      {
        kanji: "受入",
        romaji: "Ukeire",
        arti: "Penerimaan",
      },
      {
        kanji: "一般的な",
        romaji: "Ippan teki na",
        arti: "Umumnya",
      },
      {
        kanji: "衛生管理",
        romaji: "Eiseikanri",
        arti: "Manajemen Kebersihan",
      },
      {
        kanji: "製造する",
        romaji: "Seizou suru",
        arti: "Pembuatan",
      },
      {
        kanji: "有害な",
        romaji: "Yuugai na",
        arti: "Berbahaya",
      },
      {
        kanji: "化学物質",
        romaji: "Kagaku Busshitsu",
        arti: "Bahan Kimia",
      },
      {
        kanji: "含む",
        romaji: "Fukumu",
        arti: "Termasuk",
      },
      {
        kanji: "飲食品",
        romaji: "Inshokuhin",
        arti: "Makanan dan Minuman",
      },
      {
        kanji: "健康障害",
        romaji: "Kenkou Shougai",
        arti: "Bahaya Kesehatan",
      },
      {
        kanji: "下痢",
        romaji: "Geri",
        arti: "Diare",
      },
      {
        kanji: "原因",
        romaji: "Gen'in",
        arti: "Penyebab",
      },
      {
        kanji: "物質",
        romaji: "Busshitsu",
        arti: "Bahan/Zat",
      },
      {
        kanji: "細菌",
        romaji: "Saikin",
        arti: "Bakteri",
      },
      {
        kanji: "ウイルス",
        romaji: "Uirusu",
        arti: "Virus",
      },
      {
        kanji: "について",
        romaji: "Ni tsuite",
        arti: "Tentang",
      },
      {
        kanji: "紹介する",
        romaji: "Shoukai suru",
        arti: "Memperkenalkan",
      },
      {
        kanji: "分類",
        romaji: "Bunrui",
        arti: "Klasifikasi",
      },
      {
        kanji: "感染型食中毒",
        romaji: "Kansen-gata Shokuchuudoku",
        arti: "Keracunan Makanan Menular",
      },
      {
        kanji: "増える",
        romaji: "Fueru",
        arti: "Bertambah",
      },
      {
        kanji: "細胞",
        romaji: "Saibou",
        arti: "sel",
      },
      {
        kanji: "破壊する",
        romaji: "Hakai suru",
        arti: "menghancurkan",
      },
      {
        kanji: "毒素",
        romaji: "Dokuso",
        arti: "racun",
      },
      {
        kanji: "腸管出血性大腸菌",
        romaji: "Choukan Shukketsusei Daichoukin",
        arti: "bakteri ecoli",
      },
      {
        kanji: "属菌",
        romaji: "Zokukin",
        arti: "bakteri",
      },
      {
        kanji: "サルモネラ",
        romaji: "Sarumonera",
        arti: "Bakteri Salmonela",
      },
      {
        kanji: "カンピロバクター",
        romaji: "Kanpirobakutaa",
        arti: "Bakteri Kanpiro",
      },
      {
        kanji: "腸炎ビブリオ",
        romaji: "Chouen Biburio",
        arti: "Couen Biburio",
      },
      {
        kanji: "毒素型食中毒",
        romaji: "Dokuso-gata Shokuchuudoku",
        arti: "Keracunan Makanan karena Racun",
      },
      {
        kanji: "ノロウイルス",
        romaji: "Noro Uirusu",
        arti: "Noro Virus",
      },
      {
        kanji: "牡蠣",
        romaji: "Kaki",
        arti: "Kerang Tiram",
      },
      {
        kanji: "感染します",
        romaji: "Kansen shimasu",
        arti: "terinfeksi",
      },
      {
        kanji: "主な",
        romaji: "Omona",
        arti: "Utama",
      },
      {
        kanji: "症状",
        romaji: "Shoujou",
        arti: "Gejala",
      },
      {
        kanji: "予防対策",
        romaji: "Yobou Taisaku",
        arti: "Pencegahan",
      },
      {
        kanji: "激しい下痢",
        romaji: "Hageshii Geri",
        arti: "Diare Berat",
      },
      {
        kanji: "血便",
        romaji: "Ketsuben",
        arti: "Berak Darah",
      },
      {
        kanji: "腹痛",
        romaji: "Fukutsuu",
        arti: "Sakit Perut",
      },
      {
        kanji: "発熱",
        romaji: "Hatsunetsu",
        arti: "Demam Tinggi",
      },
      {
        kanji: "食肉",
        romaji: "Shokuniku",
        arti: "Daging Dagingan",
      },
      {
        kanji: "井戸水",
        romaji: "Ido Mizu",
        arti: "Air Sumur",
      },
      {
        kanji: "鶏卵",
        romaji: "Keiran",
        arti: "Telor Ayam",
      },
      {
        kanji: "海水の魚介類",
        romaji: "Kaisui no Gyokairui",
        arti: "Olahan Laut (Seafood)",
      },
      {
        kanji: "加熱します",
        romaji: "Kanetsu shimasu",
        arti: "Memanaskan",
      },
      {
        kanji: "以上",
        romaji: "Ijyou",
        arti: "Atas",
      },
      {
        kanji: "以下",
        romaji: "Ika",
        arti: "Bawah",
      },
      {
        kanji: "間",
        romaji: "Aida",
        arti: "Diantara",
      },
      {
        kanji: "洗浄する",
        romaji: "Senjou suru",
        arti: "Membersihkan dengan air",
      },
      {
        kanji: "吐気",
        romaji: "Hakike",
        arti: "Mual",
      },
      {
        kanji: "嘔吐",
        romaji: "Outo",
        arti: "Muntah",
      },
      {
        kanji: "絆",
        romaji: "Kizu",
        arti: "Luka Gores",
      },
      {
        kanji: "ちょうりします",
        romaji: "Chouri shimasu",
        arti: "Memasak",
      },
      {
        kanji: "缶",
        romaji: "Kanzume",
        arti: "Kalengan",
      },
      {
        kanji: "瓶",
        romaji: "Binzume",
        arti: "Botolan",
      },
      {
        kanji: "真空パック食品",
        romaji: "Shinku Pakku Shokuhin",
        arti: "Makanan Kemasan",
      },
      {
        kanji: "量",
        romaji: "Ryou",
        arti: "Jumlah",
      },
      {
        kanji: "保存された",
        romaji: "Hozon sareta",
        arti: "Disimpan",
      },
      {
        kanji: "保存します",
        romaji: "Hozon shimasu",
        arti: "Menyimpan",
      },
      {
        kanji: "煮物",
        romaji: "Nimono",
        arti: "Makanan Rebus",
      },
      {
        kanji: "芽胞",
        romaji: "Gahou",
        arti: "Spora",
      },
      {
        kanji: "調理後",
        romaji: "Chouri go",
        arti: "Setelah Memasak",
      },
      {
        kanji: "冷却",
        romaji: "Reikyaku",
        arti: "Mendinginkan",
      },
      {
        kanji: "高温",
        romaji: "Kouon",
        arti: "Suhu Tinggi",
      },
      {
        kanji: "低温",
        romaji: "Teion",
        arti: "Suhu rendah",
      },
      {
        kanji: "室温",
        romaji: "Shitsuon",
        arti: "suhu ruangan",
      },
      {
        kanji: "必要です",
        romaji: "Hitsuyou desu",
        arti: "PERLU",
      },
      {
        kanji: "つけない",
        romaji: "Tsukenai",
        arti: "tidak mencemari",
      },
      {
        kanji: "増やさない",
        romaji: "Fuyasanai",
        arti: "tidak menambah",
      },
      {
        kanji: "殺す",
        romaji: "Korosu (Yattsukeru)",
        arti: "membunuh",
      },
      {
        kanji: "最も",
        romaji: "Mottomo",
        arti: "lebih ….",
      },
      {
        kanji: "器具",
        romaji: "Kigu",
        arti: "instrumen",
      },
      {
        kanji: "装置",
        romaji: "Souchi",
        arti: "perangkat",
      },
      {
        kanji: "機械",
        romaji: "Kikai",
        arti: "mesin",
      },
      {
        kanji: "乾燥します",
        romaji: "Kansou shimasu",
        arti: "mengeringkan",
      },
      {
        kanji: "可能性がある",
        romaji: "Kanousei ga aru",
        arti: "ada kemungkinan",
      },
      {
        kanji: "豆",
        romaji: "Mame",
        arti: "kacang",
      },
      {
        kanji: "穀類",
        romaji: "Kokurui",
        arti: "sereal",
      },
      {
        kanji: "汚染されやすい",
        romaji: "Osen sareyasui",
        arti: "mudah tercemari",
      },
      {
        kanji: "防ぎます",
        romaji: "Fusegimasu",
        arti: "mencegah",
      },
      {
        kanji: "衛生管理",
        romaji: "Eisei Kanri",
        arti: "Manajemen Kebersihan",
      },
      {
        kanji: "健康管理",
        romaji: "Kenkou Kanri",
        arti: "Manajemen Kesehatan",
      },
      {
        kanji: "衛生",
        romaji: "Eisei",
        arti: "Kebersihan",
      },
      {
        kanji: "作業場",
        romaji: "Sagyoujou",
        arti: "Tempat Kerja",
      },
      {
        kanji: "行うこと",
        romaji: "Okonau Koto",
        arti: "Yg harus dilakukan",
      },
      {
        kanji: "個人",
        romaji: "Kojin",
        arti: "Individu",
      },
      {
        kanji: "体調",
        romaji: "Taichou",
        arti: "Kondisi (tubuh)",
      },
      {
        kanji: "風邪を引いて",
        romaji: "Kaze wo Hiite",
        arti: "Masuk angin",
      },
      {
        kanji: "必ず",
        romaji: "Kanarazu",
        arti: "Pastikan",
      },
      {
        kanji: "責任者",
        romaji: "Sekininsha",
        arti: "Manajer/Penanggung Jawab",
      },
      {
        kanji: "報告する",
        romaji: "Houkoku suru",
        arti: "Melapor",
      },
      {
        kanji: "指示",
        romaji: "Shiji",
        arti: "Perintah",
      },
      {
        kanji: "従います",
        romaji: "Shitagaimasu",
        arti: "Melaksanakan",
      },
      {
        kanji: "爪",
        romaji: "Tsume",
        arti: "Kuku",
      },
      {
        kanji: "私物",
        romaji: "Shibutsu",
        arti: "Barang Pribadi",
      },
      {
        kanji: "宝石類",
        romaji: "Housekirui",
        arti: "Perhiasan",
      },
      {
        kanji: "装飾品",
        romaji: "Soushokuhin",
        arti: "Aksesoris",
      },
      {
        kanji: "ロッカー",
        romaji: "Rokkaa",
        arti: "Loker",
      },
      {
        kanji: "保管します",
        romaji: "Hokan shimasu",
        arti: "Menyimpan",
      },
      {
        kanji: "保管されます",
        romaji: "Hokan saremasu",
        arti: "Disimpan",
      },
      {
        kanji: "外します",
        romaji: "Hazushimasu",
        arti: "Melepas",
      },
      {
        kanji: "作業服",
        romaji: "Sagyoufuku",
        arti: "Pakaian Kerja",
      },
      {
        kanji: "着用する",
        romaji: "Chakuyou suru",
        arti: "Memakai (pakaian)",
      },
      {
        kanji: "清潔な",
        romaji: "Seiketsu na",
        arti: "Bersih",
      },
      {
        kanji: "汚れた",
        romaji: "Yogoreta",
        arti: "Kotor",
      },
      {
        kanji: "くっつかないようにします",
        romaji: "Kuttsukanai you ni shimasu",
        arti: "Jangan Mencampur",
      },
      {
        kanji: "洗濯します",
        romaji: "Sentaku shimasu",
        arti: "Mencuci Pakaian",
      },
      {
        kanji: "帽子",
        romaji: "Boushi",
        arti: "Topi",
      },
      {
        kanji: "マスク",
        romaji: "Masuku",
        arti: "Masker",
      },
      {
        kanji: "洗髪",
        romaji: "Senpatsu",
        arti: "Keramas (rambut)",
      },
      {
        kanji: "定期的な",
        romaji: "Teikiteki",
        arti: "Dengan Teratur",
      },
      {
        kanji: "香水",
        romaji: "Kousui",
        arti: "Parfum",
      },
      {
        kanji: "使用します",
        romaji: "Shiyou shimasu",
        arti: "Menggunakan",
      },
      {
        kanji: "エアリング",
        romaji: "Earingu",
        arti: "Anting",
      },
      {
        kanji: "ネックレス",
        romaji: "Nekkuresu",
        arti: "Kalung",
      },
      {
        kanji: "かみはたばねます",
        romaji: "Kami wa tabanemasu",
        arti: "Mengikat Rambut",
      },
      {
        kanji: "ポケット",
        romaji: "Poketto",
        arti: "Saku",
      },
      {
        kanji: "ボタン",
        romaji: "Botan",
        arti: "Kancing",
      },
      {
        kanji: "マニキュア",
        romaji: "Manikyua",
        arti: "Cat Kuku",
      },
      {
        kanji: "指輪",
        romaji: "Yubiwa",
        arti: "Cincin",
      },
      {
        kanji: "袖ゴム",
        romaji: "Sode Gomu",
        arti: "Lengan Baju Karet",
      },
      {
        kanji: "ブラッシング",
        romaji: "Burasshingu",
        arti: "Sisir",
      },
      {
        kanji: "ヘアーネット",
        romaji: "Heaa Netto",
        arti: "HairNet",
      },
      {
        kanji: "確認します",
        romaji: "Kakunin shimasu",
        arti: "Mengkonfirmasi/Cek ulang",
      },
      {
        kanji: "毛髪",
        romaji: "Mouhatsu",
        arti: "Rambut",
      },
      {
        kanji: "粘着ローラ",
        romaji: "Nenchaku Rooraa",
        arti: "Roll Perekat",
      },
      {
        kanji: "エアーシャワー",
        romaji: "Eaa Shawaa",
        arti: "Shower Udara",
      },
      {
        kanji: "埃",
        romaji: "Hokori",
        arti: "Debu",
      },
      {
        kanji: "十分",
        romaji: "Juubun",
        arti: "Cukup",
      },
      {
        kanji: "洗剤",
        romaji: "Senzai",
        arti: "Sabun",
      },
      {
        kanji: "念入りに洗う",
        romaji: "Neniri ni arau",
        arti: "Cuci dengan Teliti",
      },
      {
        kanji: "洗い流す",
        romaji: "Arai nagasu",
        arti: "Bilas dengan Air",
      },
      {
        kanji: "使い捨てペーパー",
        romaji: "Tsukaisute Peepaa",
        arti: "Tisu Sekali Pakai",
      },
      {
        kanji: "エアータオル",
        romaji: "Eaa Taoru",
        arti: "Handuk Udara/Blower",
      },
      {
        kanji: "拭き取る",
        romaji: "Fukitoru",
        arti: "Mengelap",
      },
      {
        kanji: "消毒液",
        romaji: "Shoudokueki",
        arti: "Cairan Antiseptik",
      },
      {
        kanji: "消毒する",
        romaji: "Shoudoku suru",
        arti: "Mensterilkan",
      },
      {
        kanji: "作業靴",
        romaji: "Sagyougutsu",
        arti: "Sepatu Kerja",
      },
      {
        kanji: "扱い",
        romaji: "Atsukai",
        arti: "Penanganan",
      },
      {
        kanji: "通勤靴",
        romaji: "Tsuukingutsu",
        arti: "Sepatu Biasa",
      },
      {
        kanji: "汚染区",
        romaji: "Osenku",
        arti: "Area ter Kontaminasi",
      },
      {
        kanji: "非汚染区",
        romaji: "Hi osenku",
        arti: "Area Steril",
      },
      {
        kanji: "担当",
        romaji: "Tantou",
        arti: "Posisi",
      },
      {
        kanji: "配置表",
        romaji: "Haichihyou",
        arti: "Tabel Tata Letak",
      },
      {
        kanji: "マニュアル",
        romaji: "Manyuaru",
        arti: "Buku Panduan",
      },
      {
        kanji: "作業手順書",
        romaji: "Sagyou Tejunsho",
        arti: "Buku Panduan",
      },
      {
        kanji: "機械",
        romaji: "Kikai",
        arti: "Mesin",
      },
      {
        kanji: "装置",
        romaji: "Souchi",
        arti: "Perangkat",
      },
      {
        kanji: "器具",
        romaji: "Kigu",
        arti: "Instrumen / Alat",
      },
      {
        kanji: "汚れた",
        romaji: "Yogoreta",
        arti: "Kotor",
      },
      {
        kanji: "不備",
        romaji: "Fubi",
        arti: "Cacat/Rusak",
      },
      {
        kanji: "点検表",
        romaji: "Tenkenhyou",
        arti: "Daftar Pemeriksaan",
      },
      {
        kanji: "洗浄剤",
        romaji: "Senjouzai",
        arti: "Bahan Pembersih",
      },
      {
        kanji: "殺菌剤",
        romaji: "Sakkinzai",
        arti: "Bahan Antiseptik",
      },
      {
        kanji: "洗浄",
        romaji: "Senjou",
        arti: "Pembersihan",
      },
      {
        kanji: "殺菌",
        romaji: "Sakkin",
        arti: "Pensterilisasian",
      },
      {
        kanji: "残らないように",
        romaji: "Nokoranai you ni",
        arti: "Jangan Tersisa",
      },
      {
        kanji: "作業中",
        romaji: "Sagyouchuu",
        arti: "Saat Bekerja",
      },
      {
        kanji: "注意事項",
        romaji: "Chuui jikou",
        arti: "Tindakan Pencegahan",
      },
      {
        kanji: "よそ見しないように",
        romaji: "Yosomi shinai you ni",
        arti: "Jangan Berpaling",
      },
      {
        kanji: "ムダなはなし",
        romaji: "Muda na hanashi",
        arti: "Obrolan tidak bermutu",
      },
      {
        kanji: "不自然な姿勢",
        romaji: "Fushizen na shisei",
        arti: "Postur tidak sesuai",
      },
      {
        kanji: "合図",
        romaji: "Aizu",
        arti: "Tanda",
      },
      {
        kanji: "行います",
        romaji: "Okonaimasu",
        arti: "Melakukan",
      },
      {
        kanji: "危険",
        romaji: "Kiken",
        arti: "Bahaya",
      },
      {
        kanji: "箇所",
        romaji: "Kasho",
        arti: "Bagian",
      },
      {
        kanji: "見つかった",
        romaji: "Mitsukatta",
        arti: "Ditemukan",
      },
      {
        kanji: "注意します",
        romaji: "Chuui shimasu",
        arti: "Memperingatkan",
      },
      {
        kanji: "無断",
        romaji: "Mudan",
        arti: "Seenaknya",
      },
      {
        kanji: "離れます",
        romaji: "Hanaremasu",
        arti: "Kabur",
      },
      {
        kanji: "指差呼称",
        romaji: "Shisa Koshou",
        arti: "Menunjuk dgn Jari dan Mengucap",
      },
      {
        kanji: "機械操作",
        romaji: "Kikai Sousa",
        arti: "Pengoperasian Mesin",
      },
      {
        kanji: "くぐらないようにします",
        romaji: "Kuguranai you ni shimasu",
        arti: "Jangan Ngglundung lwt Bawah",
      },
      {
        kanji: "運転方法",
        romaji: "Unten Houhou",
        arti: "Cara Pengoperasian",
      },
      {
        kanji: "動いている",
        romaji: "Ugoiteiru",
        arti: "Bergerak",
      },
      {
        kanji: "異常",
        romaji: "Ijou",
        arti: "Tidak Normal",
      },
      {
        kanji: "停電",
        romaji: "Teiden",
        arti: "Mati Listrik",
      },
      {
        kanji: "スイッチ",
        romaji: "Suicchi",
        arti: "Saklar",
      },
      {
        kanji: "認識する",
        romaji: "Ninshiki suru",
        arti: "Mengenali",
      },
      {
        kanji: "使用器具",
        romaji: "Shiyou Kigu",
        arti: "Alat yang digunakan",
      },
      {
        kanji: "石鹼",
        romaji: "Sekken",
        arti: "Sabun",
      },
      {
        kanji: "製品",
        romaji: "Seihin",
        arti: "Produk",
      },
      {
        kanji: "放置しないようにします",
        romaji: "Houchi shinai you ni shimasu",
        arti: "Jangan Dibiarkan/Ditinggal",
      },
      {
        kanji: "接触しないようにする",
        romaji: "Sesshoku shinai you ni suru",
        arti: "Hindari Kontak",
      },
      {
        kanji: "製造ライン",
        romaji: "Seizou Rain",
        arti: "Jalur Produksi",
      },
      {
        kanji: "作業後",
        romaji: "Sagyougo",
        arti: "Setelah bekerja",
      },
      {
        kanji: "シフト交代",
        romaji: "Shifuto Koutai",
        arti: "Pergantian Shift",
      },
      {
        kanji: "乾燥させます",
        romaji: "Kansou sasemasu",
        arti: "Dikeringkan",
      },
      {
        kanji: "５S活動",
        romaji: "Go Esu Katsudou",
        arti: "Budaya 5S",
      },
      {
        kanji: "整理",
        romaji: "Seiri",
        arti: "Pengorganisasian",
      },
      {
        kanji: "整頓",
        romaji: "Seiton",
        arti: "Merapihkan",
      },
      {
        kanji: "清掃",
        romaji: "Seisou",
        arti: "Pembersihan",
      },
      {
        kanji: "清潔",
        romaji: "Seiketsu",
        arti: "Kebersihan",
      },
      {
        kanji: "習慣",
        romaji: "Shuukan/Shitsuke",
        arti: "Kebiasaan",
      },
      {
        kanji: "異物混入",
        romaji: "Ibutsu Konnyuu",
        arti: "Kontaminasi Benda Asing",
      },
      {
        kanji: "金属",
        romaji: "Kinzoku",
        arti: "Logam",
      },
      {
        kanji: "ガラス",
        romaji: "Garasu",
        arti: "Kaca",
      },
      {
        kanji: "虫",
        romaji: "Mushi",
        arti: "Serangga",
      },
      {
        kanji: "髪の毛",
        romaji: "Kami no ke",
        arti: "Rambut",
      },
      {
        kanji: "考え方",
        romaji: "Kangaekata",
        arti: "Konsep / Cara Berpikir",
      },
      {
        kanji: "不可欠",
        romaji: "Fukaketsu",
        arti: "Penting",
      },
      {
        kanji: "及ぼす",
        romaji: "Oyobosu",
        arti: "Berpengaruh",
      },
      {
        kanji: "製造工程",
        romaji: "Seizou Koutei",
        arti: "Proses Produksi",
      },
      {
        kanji: "段階",
        romaji: "Dankai",
        arti: "Langkah",
      },
      {
        kanji: "適切に",
        romaji: "Tekisetsu ni",
        arti: "Dengan Baik",
      },
      {
        kanji: "明確にする",
        romaji: "Meikaku ni suru",
        arti: "Untuk Memperjelas",
      },
      {
        kanji: "危害",
        romaji: "Kigai",
        arti: "Bahaya",
      },
      {
        kanji: "危害分析",
        romaji: "Kigai Bunseki",
        arti: "Analisis Bahaya",
      },
      {
        kanji: "危害の要因",
        romaji: "Kigai no Youin",
        arti: "Faktor Bahaya",
      },
      {
        kanji: "過去",
        romaji: "Kako",
        arti: "Sebelumnya / Lampau",
      },
      {
        kanji: "検査結果",
        romaji: "Kensa Kekka",
        arti: "Hasil Tes",
      },
      {
        kanji: "関連する文献",
        romaji: "Kanren suru Bunken",
        arti: "Literatur Terkait",
      },
      {
        kanji: "資料",
        romaji: "Shiryou",
        arti: "Dokumen",
      },
      {
        kanji: "混入する",
        romaji: "Konnyuu suru",
        arti: "Terkontaminasi",
      },
      {
        kanji: "程度のリスク",
        romaji: "Teido no Risuku",
        arti: "Tingkat Resiko",
      },
      {
        kanji: "受入",
        romaji: "Ukeire",
        arti: "Penerimaan",
      },
      {
        kanji: "検査",
        romaji: "Kensa",
        arti: "Inspeksi",
      },
      {
        kanji: "対処すべき",
        romaji: "Taisho subeki",
        arti: "Harus Ditangani",
      },
      {
        kanji: "判断する",
        romaji: "Handan suru",
        arti: "Untuk Memutuskan",
      },
      {
        kanji: "データ",
        romaji: "Deeta",
        arti: "Data",
      },
      {
        kanji: "応じた",
        romaji: "Oujita",
        arti: "Memenuhi",
      },
      {
        kanji: "仕掛品",
        romaji: "Shikakarihin",
        arti: "Barang dalam Proses",
      },
      {
        kanji: "中間製品",
        romaji: "Chuukan Seihin",
        arti: "Produk Setengah Jadi",
      },
      {
        kanji: "関係があります",
        romaji: "Kankei ga arimasu",
        arti: "Ada Hubungannya",
      },
      {
        kanji: "急速に増殖する",
        romaji: "Kyuusoku ni Zoushoku suru",
        arti: "Berkembang biak dengan cepat",
      },
      {
        kanji: "増殖しにくくなる",
        romaji: "Zoushoku shinikuku naru",
        arti: "Sulit berkembang biak",
      },
      {
        kanji: "短くする",
        romaji: "Mijikaku suru",
        arti: "Dipersingkat",
      },
      {
        kanji: "速やかに",
        romaji: "Sumiyaka ni",
        arti: "Dengan Cepat",
      },
      {
        kanji: "冷却する",
        romaji: "Reikyaku suru",
        arti: "Mendinginkan",
      },
      {
        kanji: "冷蔵庫",
        romaji: "Reizouko",
        arti: "Lemari Pendingin",
      },
      {
        kanji: "冷凍庫",
        romaji: "Reitouko",
        arti: "Lemari Pembeku",
      },
      {
        kanji: "規定",
        romaji: "Kitei",
        arti: "Peraturan",
      },
      {
        kanji: "食品衛生法",
        romaji: "Shokuhin Eiseihou",
        arti: "Undang-undang sanitasi Makanan",
      },
      {
        kanji: "測定",
        romaji: "Sokutei",
        arti: "Pengukuran",
      },
      {
        kanji: "記録する",
        romaji: "Kiroku suru",
        arti: "Mencatat",
      },
      {
        kanji: "加熱工程",
        romaji: "Kanetsu Koutei",
        arti: "Proses Pemanasan",
      },
      {
        kanji: "死滅します",
        romaji: "Shimetsu shimasu",
        arti: "Mati",
      },
      {
        kanji: "ほとんど",
        romaji: "Hotondo",
        arti: "Hampir",
      },
      {
        kanji: "しかし",
        romaji: "Shikashi",
        arti: "Namun/Tapi",
      },
      {
        kanji: "芽胞菌",
        romaji: "Gahoukin",
        arti: "Bakteri pembawa Spora",
      },
      {
        kanji: "設定します",
        romaji: "Settei shimasu",
        arti: "Mengatur / Menyetting",
      },
      {
        kanji: "対象",
        romaji: "Taishou",
        arti: "Target",
      },
      {
        kanji: "中心温度計",
        romaji: "Chuushin Ondokei",
        arti: "Suhu Terpusat",
      },
      {
        kanji: "冷却工程",
        romaji: "Reikyaku Koutei",
        arti: "Proses Pendinginan",
      },
      {
        kanji: "風を当てて冷やす方法",
        romaji: "Kaze wo atete hiyasu houhou",
        arti: "mendinginkan dengan angin",
      },
      {
        kanji: "冷水で冷やす方法",
        romaji: "Reisui de hiyasu houhou",
        arti: "mendinginkan dengan air dingin",
      },
      {
        kanji: "冷水",
        romaji: "Reisui",
        arti: "Air Dingin",
      },
      {
        kanji: "冷やします",
        romaji: "Hiyashimasu",
        arti: "Mendinginkan",
      },
      {
        kanji: "凍結工程",
        romaji: "Touketsu Koutei",
        arti: "Proses Pembekuan",
      },
      {
        kanji: "風味",
        romaji: "Fuumi",
        arti: "Rasa",
      },
      {
        kanji: "テクスチャー",
        romaji: "Tekusuchaa",
        arti: "Tekstur",
      },
      {
        kanji: "劣化します",
        romaji: "Rekka shimasu",
        arti: "Menurun",
      },
      {
        kanji: "凍結温度",
        romaji: "Touketsu Ondo",
        arti: "Suhu Beku",
      },
      {
        kanji: "低温",
        romaji: "Teion",
        arti: "Suhu Rendah",
      },
      {
        kanji: "短時間",
        romaji: "Tanjikan",
        arti: "Waktu Singkat",
      },
      {
        kanji: "包装工程",
        romaji: "Housou Koutei",
        arti: "Proses Pengemasan",
      },
      {
        kanji: "金属検出器",
        romaji: "Kinzoku Kenshutsuki",
        arti: "Detektor Logam",
      },
      {
        kanji: "X線異物検出器",
        romaji: "Ekkusu-sen Ibutsu Kenshutsuki",
        arti: "Detektor Sinar X",
      },
      {
        kanji: "期限表示",
        romaji: "Kigen Hyouji",
        arti: "Tanggal Kadaluwarsa",
      },
      {
        kanji: "石",
        romaji: "Ishi",
        arti: "Batu",
      },
      {
        kanji: "製品の管理",
        romaji: "Seihin no Kanri",
        arti: "Manajemen Produk",
      },
      {
        kanji: "検査項目",
        romaji: "Kensa Koumoku",
        arti: "Barang Inspeksi",
      },
      {
        kanji: "基準",
        romaji: "Kijun",
        arti: "Standar",
      },
      {
        kanji: "法律",
        romaji: "Houritsu",
        arti: "Hukum",
      },
      {
        kanji: "定めます",
        romaji: "Sadame masu",
        arti: "Menetapkan",
      },
      {
        kanji: "自主的な",
        romaji: "Jishuteki na",
        arti: "Sukarela",
      },
      {
        kanji: "菌数",
        romaji: "Kinsuu",
        arti: "Jumlah Bakteri",
      },
      {
        kanji: "主体としています",
        romaji: "Shutai to shiteimasu",
        arti: "Terutama",
      },
      {
        kanji: "保管サンプル",
        romaji: "Hokan Sanpuru",
        arti: "Sampel yang disimpan",
      },
      {
        kanji: "クレーム",
        romaji: "Kureemu",
        arti: "Klaim",
      },
      {
        kanji: "発生した",
        romaji: "Hassei shita",
        arti: "Terjadi",
      },
      {
        kanji: "備えて",
        romaji: "Sonaete",
        arti: "Bersiap untuk",
      },
      {
        kanji: "割合",
        romaji: "Wariai",
        arti: "Membagi",
      },
      {
        kanji: "望ましい",
        romaji: "Nozomashii",
        arti: "Diinginkan",
      },
      {
        kanji: "製造日",
        romaji: "Seizoubi",
        arti: "Tanggal Produksi",
      },
      {
        kanji: "輸送時",
        romaji: "Yusouji",
        arti: "Waktu Pengiriman/Transport",
      },
      {
        kanji: "変化",
        romaji: "Henka",
        arti: "Berubah",
      },
      {
        kanji: "冷蔵車",
        romaji: "Reizousha",
        arti: "Truk Pendingin",
      },
      {
        kanji: "冷凍車",
        romaji: "Reitousha",
        arti: "Truk Pembeku",
      },
      {
        kanji: "アレルギー",
        romaji: "Arerugii",
        arti: "Alergi",
      },
      {
        kanji: "特定原材料",
        romaji: "Tokutei Genzairyou",
        arti: "Bahan Baku Khusus",
      },
      {
        kanji: "乳",
        romaji: "Nyuu",
        arti: "Susu",
      },
      {
        kanji: "落花生",
        romaji: "Rakkasei",
        arti: "Kacang Tanah",
      },
      {
        kanji: "アーモンド",
        romaji: "Aamondo",
        arti: "Kacang Almond",
      },
      {
        kanji: "鮑",
        romaji: "Awabi",
        arti: "Abalon",
      },
      {
        kanji: "いか",
        romaji: "Ika",
        arti: "Cumi",
      },
      {
        kanji: "いくら",
        romaji: "Ikura",
        arti: "Telur Salmon",
      },
      {
        kanji: "カシューナッツ",
        romaji: "Kashuu Nattsu",
        arti: "Kacang Mede",
      },
      {
        kanji: "くるみ",
        romaji: "Kurumi",
        arti: "Biji Kenari",
      },
      {
        kanji: "ごま",
        romaji: "Goma",
        arti: "Wijen",
      },
      {
        kanji: "さけ",
        romaji: "Sake",
        arti: "Ikan Salmon",
      },
      {
        kanji: "さば",
        romaji: "Saba",
        arti: "Ikan Kembung",
      },
      {
        kanji: "大豆",
        romaji: "Daizu",
        arti: "Kedelai",
      },
      {
        kanji: "まつたけ",
        romaji: "Matsutake",
        arti: "Jamur Matsutake",
      },
      {
        kanji: "もも",
        romaji: "Momo",
        arti: "Buah Peach",
      },
      {
        kanji: "やまいも",
        romaji: "Yamaimo",
        arti: "Ubi Jepang",
      },
      {
        kanji: "ゼラチン",
        romaji: "Zerachin",
        arti: "Agar-agar",
      },
      {
        kanji: "交差汚染",
        romaji: "Kousa Osen",
        arti: "Kontaminasi Silang",
      },
      {
        kanji: "他の製品",
        romaji: "Ta no Seihin",
        arti: "Produk lain",
      },
      {
        kanji: "区分",
        romaji: "Kubun",
        arti: "Memisahkan",
      },
      {
        kanji: "容器",
        romaji: "Youki",
        arti: "Wadah",
      },
      {
        kanji: "使い分けます",
        romaji: "Tsukaiwakemasu",
        arti: "Penggunaan yg dipisah",
      },
      {
        kanji: "色分けします",
        romaji: "Irowake shimasu",
        arti: "Membagi dengan warna",
      },
      {
        kanji: "マークをつける",
        romaji: "Maaku wo tsukeru",
        arti: "Memberi Tanda/Mark",
      },
      {
        kanji: "重ねます",
        romaji: "Kasanemasu",
        arti: "Menindih/Menumpuk",
      },
      {
        kanji: "開封済みの物",
        romaji: "Kaifuu zumi no mono",
        arti: "Produk yang dibuka",
      },
      {
        kanji: "可能性",
        romaji: "Kanousei",
        arti: "Kemungkinan",
      },
      {
        kanji: "中身",
        romaji: "Nakami",
        arti: "Dalam/isian",
      },
      {
        kanji: "薬剤",
        romaji: "Yakuzai",
        arti: "Obat Kimia/Bahan Kimia",
      },
      {
        kanji: "薬剤専用",
        romaji: "Yakuzai Senyou",
        arti: "Khusus Bahan Kimia",
      },
      {
        kanji: "保管場所",
        romaji: "Hokan Basho",
        arti: "Tempat Penyimpanan",
      },
      {
        kanji: "入出庫台帳",
        romaji: "Nyuushukko Daichou",
        arti: "Buku Besar Keluar Masuk",
      },
      {
        kanji: "薬剤名",
        romaji: "Yakuzai Mei",
        arti: "Penamaan Bahan Kimia",
      },
      {
        kanji: "誤った使用",
        romaji: "Ayamatta Shiyou",
        arti: "Penggunaan yang salah",
      },
      {
        kanji: "ラベル",
        romaji: "Raberu",
        arti: "Label",
      },
      {
        kanji: "義務",
        romaji: "Gimu",
        arti: "Wajib",
      },
      {
        kanji: "表示",
        romaji: "Hyouji",
        arti: "Label/Tanda",
      },
      {
        kanji: "ハサップ",
        romaji: "HACCP",
        arti: "HACCP",
      },
      {
        kanji: "略語",
        romaji: "Ryakugo",
        arti: "SINGKATAN",
      },
      {
        kanji: "危害要因分析",
        romaji: "Kigai Youin Bunseki",
        arti: "ANALISIS BAHAYA",
      },
      {
        kanji: "明らかにする",
        romaji: "Akiraka ni suru",
        arti: "MENERANGKAN",
      },
      {
        kanji: "ミスする",
        romaji: "Misu suru",
        arti: "MENINGGALKAN",
      },
      {
        kanji: "製造工程",
        romaji: "Seizou Koutei",
        arti: "PROSES PRODUKSI",
      },
      {
        kanji: "管理点",
        romaji: "Kanriten",
        arti: "TITIK KONTROL",
      },
      {
        kanji: "最終製品",
        romaji: "Saishuu Seihin",
        arti: "PRODUK UTAMA",
      },
      {
        kanji: "出荷",
        romaji: "Shukka",
        arti: "PENGIRIMAN",
      },
      {
        kanji: "効果的な",
        romaji: "Koukateki na",
        arti: "EFEKTIF",
      },
      {
        kanji: "連続的な",
        romaji: "Renzokuteki na",
        arti: "CONTINUE",
      },
      {
        kanji: "生物的危害要因",
        romaji: "Seibutsuteki Kigai Youin",
        arti: "BAHAYA BIOLOGIS",
      },
      {
        kanji: "化学的危害要因",
        romaji: "Kagakuteki Kigai Youin",
        arti: "BAHAYA KIMIA",
      },
      {
        kanji: "物理的危害要因",
        romaji: "Butsuriteki Kigai Youin",
        arti: "BAHAYA FISIK",
      },
      {
        kanji: "農薬",
        romaji: "Nouyaku",
        arti: "PESTISIDA",
      },
      {
        kanji: "抗生物質",
        romaji: "Kousei Busshitsu",
        arti: "ANTIBIOTIK",
      },
      {
        kanji: "原則",
        romaji: "Gensoku",
        arti: "PRINSIP",
      },
      {
        kanji: "重要管理点",
        romaji: "Juuyou Kanriten",
        arti: "CCP.TITIK KONTROL KRITIS",
      },
      {
        kanji: "リストアップする",
        romaji: "Risuto Appu suru",
        arti: "MEMBUAT DAFTAR",
      },
      {
        kanji: "決定",
        romaji: "Kettei",
        arti: "PENENTUAN",
      },
      {
        kanji: "加熱殺菌工程",
        romaji: "Kanetsu Sakkin Koutei",
        arti: "STERILISASI PANAS",
      },
      {
        kanji: "金属検出器",
        romaji: "Kinzoku Kenshutsuki",
        arti: "DETEKTOR LOGAM",
      },
      {
        kanji: "X線検出器",
        romaji: "Ekkusu-sen Kenshutsuki",
        arti: "DETEKTOR SINAR X",
      },
      {
        kanji: "管理基準",
        romaji: "Kanri Kijun",
        arti: "STANDAR MANAJEMEN",
      },
      {
        kanji: "設定",
        romaji: "Settei",
        arti: "PENGATURAN",
      },
      {
        kanji: "監視",
        romaji: "Kanshi (Monitoring)",
        arti: "PEMANTAUAN",
      },
      {
        kanji: "確保する",
        romaji: "Kakuho suru",
        arti: "MENGAMANKAN",
      },
      {
        kanji: "修正措置の設定",
        romaji: "Shuusei Sochi no Settei",
        arti: "MENETAPKAN TINDAKAN KOREKTIF",
      },
      {
        kanji: "検証方法",
        romaji: "Kenshou Houhou",
        arti: "METODE VERIFIKASI",
      },
      {
        kanji: "計画",
        romaji: "Keikaku",
        arti: "RENCANA",
      },
      {
        kanji: "適切な",
        romaji: "Tekisetsu na",
        arti: "SESUAI",
      },
      {
        kanji: "作成されます",
        romaji: "Sakusei saremasu",
        arti: "DIBUAT",
      },
      {
        kanji: "記録維持管理",
        romaji: "Kiroku no Iji Kanri",
        arti: "MENCATAT PEMELIHARAAN",
      },
      {
        kanji: "保管期間",
        romaji: "Hokan Kikan",
        arti: "PERIODE PENYIMPANAN",
      },
      {
        kanji: "明確にする",
        romaji: "Meikaku ni suru",
        arti: "DENGAN JELAS",
      },
      {
        kanji: "ステンレス",
        romaji: "Sutenresu",
        arti: "STEINLESS",
      },
      {
        kanji: "鉄",
        romaji: "Tetsu",
        arti: "BESI",
      },
      {
        kanji: "業務",
        romaji: "Gyoumu",
        arti: "TUGAS",
      },
      {
        kanji: "記録する",
        romaji: "Kiroku suru",
        arti: "MENCATAT",
      },
      {
        kanji: "労働",
        romaji: "Roudou",
        arti: "KERJA",
      },
      {
        kanji: "労働者",
        romaji: "Roudousha",
        arti: "PEKERJA",
      },
      {
        kanji: "事業者",
        romaji: "Jigyousha",
        arti: "PELAKU INDUSTRI",
      },
      {
        kanji: "飲食料品製造業",
        romaji: "Inshokuryouhin Seizougyou",
        arti: "industri makanan minuman",
      },
      {
        kanji: "労働安全衛生法",
        romaji: "Roudou Anzen Eiseihou",
        arti: "UU KESELAMATAN,KESEHATAN PEKERJA",
      },
      {
        kanji: "安全管理者",
        romaji: "Anzen Kanrisha",
        arti: "MANAGER KEAMANAN",
      },
      {
        kanji: "衛生管理者",
        romaji: "Eisei Kanrisha",
        arti: "MANAGER KEBERSIHAN",
      },
      {
        kanji: "自ら",
        romaji: "Mizukara",
        arti: "DIRI",
      },
      {
        kanji: "労働災害",
        romaji: "Roudou Saigai",
        arti: "KECELAKAAN KERJA",
      },
      {
        kanji: "経験",
        romaji: "Keiken",
        arti: "PENGALAMAN",
      },
      {
        kanji: "慣れました",
        romaji: "Naremashita",
        arti: "TERBIASA",
      },
      {
        kanji: "様々",
        romaji: "Samazama",
        arti: "MACAM-MACAM",
      },
      {
        kanji: "災害",
        romaji: "Saigai",
        arti: "KECELAKAAN KERJA",
      },
      {
        kanji: "はさまれ",
        romaji: "Hasamare",
        arti: "TERJEPIT",
      },
      {
        kanji: "巻き込まれ",
        romaji: "Makikomare",
        arti: "TERSELIP,TERGULUNG",
      },
      {
        kanji: "転倒",
        romaji: "Tentou",
        arti: "TERJATUH",
      },
      {
        kanji: "切れ",
        romaji: "Kire",
        arti: "TERPOTONG",
      },
      {
        kanji: "こすれ",
        romaji: "Kosure",
        arti: "TERKIKIS",
      },
      {
        kanji: "安全装置",
        romaji: "Anzen Souchi",
        arti: "PERANGKAT KEAMANAN",
      },
      {
        kanji: "非常スイッチ",
        romaji: "Hijou Suicchi",
        arti: "SAKLAR DARURAT",
      },
      {
        kanji: "かもしれない",
        romaji: "Kamoshirenai",
        arti: "KEMUNGKINAN",
      },
      {
        kanji: "意識する",
        romaji: "Ishiki suru",
        arti: "KEWASPADAAN/KESADARAN",
      },
      {
        kanji: "当たる",
        romaji: "Ataru",
        arti: "TERBENTUR/TERTABRAK",
      },
      {
        kanji: "転ぶ",
        romaji: "Korobu",
        arti: "NGGLUNDUNG",
      },
      {
        kanji: "落ちる",
        romaji: "Ochiru",
        arti: "TERJATUH",
      },
      {
        kanji: "火傷する",
        romaji: "Yakedo suru",
        arti: "TERBAKAR",
      },
      {
        kanji: "感電する",
        romaji: "Kanden suru",
        arti: "KESETRUM",
      },
      {
        kanji: "腰を痛める",
        romaji: "Koshi wo itameru",
        arti: "NYERI PINGGANG",
      },
      {
        kanji: "ガス中毒になる",
        romaji: "Gasu Chuudoku ni naru",
        arti: "KERACUNAN GAS",
      },
      {
        kanji: "酸欠になる",
        romaji: "Sanketsu ni naru",
        arti: "KEKURANGAN OKSIGEN",
      },
      {
        kanji: "有害物にやられる",
        romaji: "Yuugaibutsu ni yareru",
        arti: "KERACUNAN GAS",
      },
      {
        kanji: "動く",
        romaji: "Ugoku",
        arti: "BERGERAK",
      },
      {
        kanji: "回る",
        romaji: "Mawaru",
        arti: "BERPUTAR",
      },
      {
        kanji: "飛ぶ",
        romaji: "Tobu",
        arti: "TERBANG",
      },
      {
        kanji: "抜ける",
        romaji: "Nukeru",
        arti: "",
      },
      {
        kanji: "燃える",
        romaji: "Moeru",
        arti: "TERBAKAR",
      },
      {
        kanji: "倒れる",
        romaji: "Taoreru",
        arti: "ROBOH",
      },
      {
        kanji: "崩れる",
        romaji: "Kuzureru",
        arti: "JATUH",
      },
      {
        kanji: "爆発",
        romaji: "Bakuhatsu",
        arti: "MELEDAK",
      },
      {
        kanji: "漏れる",
        romaji: "Moreru",
        arti: "BOCOR",
      },
      {
        kanji: "服装",
        romaji: "Fukusou",
        arti: "PAKAIAN",
      },
      {
        kanji: "定められた",
        romaji: "Sadamerareta",
        arti: "DITETAPKAN",
      },
      {
        kanji: "長袖",
        romaji: "Nagasode",
        arti: "LENGAN PANJANG",
      },
      {
        kanji: "袖口",
        romaji: "Sodeguchi",
        arti: "MANSET",
      },
      {
        kanji: "上着",
        romaji: "Uwagi",
        arti: "ATASAN",
      },
      {
        kanji: "刃物",
        romaji: "Hamon",
        arti: "BENDA TAJAM",
      },
      {
        kanji: "ドライバー",
        romaji: "Doraibaa",
        arti: "OBENG",
      },
      {
        kanji: "手ぬぐい",
        romaji: "Tenugui",
        arti: "LAP TANGAN",
      },
      {
        kanji: "首",
        romaji: "Kubi",
        arti: "LEHER",
      },
      {
        kanji: "えりまき",
        romaji: "Erimaki",
        arti: "SYAL",
      },
      {
        kanji: "ヘルメット",
        romaji: "Herumetto",
        arti: "HELM",
      },
      {
        kanji: "保護具",
        romaji: "Hogogu",
        arti: "ALAT PELINDUNG",
      },
      {
        kanji: "あごひも",
        romaji: "Agohimo",
        arti: "TALI HELM",
      },
      {
        kanji: "緩み",
        romaji: "Yurumi",
        arti: "KENDOR",
      },
      {
        kanji: "チェックする",
        romaji: "Chekku suru",
        arti: "MENGECEK",
      },
      {
        kanji: "絆",
        romaji: "Kizu",
        arti: "GORESAN/RUSAK",
      },
      {
        kanji: "保護メガネ",
        romaji: "Hogo Megane",
        arti: "KACAMATA SAFETY",
      },
      {
        kanji: "耳栓",
        romaji: "Mimisen",
        arti: "PENUTUP TELINGA",
      },
      {
        kanji: "袖をしめる",
        romaji: "Sode wo shimeru",
        arti: "MENUTUP LENGAN BAJU",
      },
      {
        kanji: "安全靴",
        romaji: "Anzen Gutsu",
        arti: "SEPATU SAFETY",
      },
      {
        kanji: "無効にします",
        romaji: "Mukou ni shimasu",
        arti: "BERPALING",
      },
      {
        kanji: "繰り返し",
        romaji: "Kurikaeshi",
        arti: "DIULANG ULANG",
      },
      {
        kanji: "安全上",
        romaji: "Anzenjou",
        arti: "KESELAMATAN",
      },
      {
        kanji: "やるべきこと",
        romaji: "Yarubeki koto",
        arti: "HAL YANG HARUS DILAKUKAN",
      },
      {
        kanji: "災害防止のポイント",
        romaji: "Saigai Boushi no Pointo",
        arti: "POINT PENCEGAHAN KECELAKAAN",
      },
      {
        kanji: "不意の起動",
        romaji: "Fui no Kidou",
        arti: "STARTUP TIBA2",
      },
      {
        kanji: "修理中",
        romaji: "Shuurichuu",
        arti: "SEDANG DIPERBAIKI",
      },
      {
        kanji: "囲い",
        romaji: "Kakoi",
        arti: "ENKLOSUR",
      },
      {
        kanji: "床",
        romaji: "Yuka",
        arti: "LANTAI",
      },
      {
        kanji: "濡れる",
        romaji: "Nureru",
        arti: "BASAH/LICIN",
      },
      {
        kanji: "拭き取る",
        romaji: "Fukitoru",
        arti: "MENGELAP/NGEPEL",
      },
      {
        kanji: "台車",
        romaji: "Daisha",
        arti: "GEROBAK",
      },
      {
        kanji: "移動する",
        romaji: "Idou suru",
        arti: "BERPINDAH",
      },
      {
        kanji: "通路",
        romaji: "Tsuuro",
        arti: "JALAN SEMPIT/LORONG",
      },
      {
        kanji: "照明",
        romaji: "Shoumei",
        arti: "PENERANGAN",
      },
      {
        kanji: "確保します",
        romaji: "Kakuho shimasu",
        arti: "MENGAMANKAN",
      },
      {
        kanji: "停止",
        romaji: "Teishi",
        arti: "MATI (MESIN)",
      },
      {
        kanji: "食品加工",
        romaji: "Shokuhin Kakou",
        arti: "PENGOLAHAN MAKANAN",
      },
      {
        kanji: "包丁",
        romaji: "Houchou",
        arti: "PISAU DAPUR",
      },
      {
        kanji: "熱中症",
        romaji: "Necchuushou",
        arti: "HEAT STROKE",
      },
      {
        kanji: "高温多湿",
        romaji: "Kouon Tashitsu",
        arti: "SUHU TINGGI",
      },
      {
        kanji: "睡眠不足",
        romaji: "Suimin Busoku",
        arti: "KEKURANGAN TIDUR",
      },
      {
        kanji: "体調の変化",
        romaji: "Taichou no Henka",
        arti: "PERUBAHAN KONDISI TUBUH",
      },
      {
        kanji: "周囲",
        romaji: "Shuui",
        arti: "LINGKUNGAN SEKITAR",
      },
      {
        kanji: "通気性",
        romaji: "Tsuukisei",
        arti: "BERVENTILASI",
      },
      {
        kanji: "吸湿性",
        romaji: "Kyuushitsusei",
        arti: "MUDAH MENYERAP",
      },
      {
        kanji: "速乾性",
        romaji: "Sokkansei",
        arti: "CEPAT KERING",
      },
      {
        kanji: "服",
        romaji: "Fuku",
        arti: "PAKAIAN",
      },
      {
        kanji: "休憩",
        romaji: "Kyuukei",
        arti: "ISTIRAHAT SEJENAK",
      },
      {
        kanji: "水分補給",
        romaji: "Suibun Hokyuu",
        arti: "MINUM AIR PUTIH",
      },
      {
        kanji: "めまい",
        romaji: "Memai",
        arti: "MUMET",
      },
      {
        kanji: "手足のしびれ",
        romaji: "Teashi no shibire",
        arti: "MATI RASA",
      },
      {
        kanji: "筋肉のこむら返り",
        romaji: "Kinniku no komuragaeri",
        arti: "OTOT KAKU",
      },
      {
        kanji: "頭痛",
        romaji: "Zutsuu",
        arti: "SAKIT KEPALA",
      },
      {
        kanji: "返事がおかしい",
        romaji: "Henji ga okashii",
        arti: "JAWABNYA ANEH",
      },
      {
        kanji: "意識消失",
        romaji: "Ishiki Shoushitsu",
        arti: "KEHILANGAN KESADARAN",
      },
      {
        kanji: "痙攣",
        romaji: "Keiren",
        arti: "KEJANG",
      },
      {
        kanji: "体が熱い",
        romaji: "Karada ga atsui",
        arti: "TUBUHNYA PANAS",
      },
      {
        kanji: "避難させます",
        romaji: "Hinan sasemasu",
        arti: "DIEVAKUASI",
      },
      {
        kanji: "衣服をゆるめる",
        romaji: "Ifuku wo yurumeru",
        arti: "PAKAIAN NYA DILONGGARKAN",
      },
      {
        kanji: "冷やします",
        romaji: "Hiyashimasu",
        arti: "MENDINGINKAN",
      },
      {
        kanji: "脇の下",
        romaji: "Waki no shita",
        arti: "BAWAH KETIAK",
      },
      {
        kanji: "足の付け根",
        romaji: "Ashi no tsukene",
        arti: "SELANGKANGAN",
      },
      {
        kanji: "塩分",
        romaji: "Enbun",
        arti: "GARAM",
      },
      {
        kanji: "溶かしました",
        romaji: "Tokashimashita",
        arti: "MELARUTKAN",
      },
      {
        kanji: "自力",
        romaji: "Jiriki",
        arti: "DENGAN SENDIRI",
      },
      {
        kanji: "救急車",
        romaji: "Kyuukyuusha",
        arti: "AMBULANCE",
      },
      {
        kanji: "腰痛症",
        romaji: "Youtsuushou",
        arti: "NYERI PUNGGUNG BAWAH",
      },
      {
        kanji: "作業姿勢",
        romaji: "Sagyou Shisei",
        arti: "POSTUR KERJA",
      },
      {
        kanji: "動作",
        romaji: "Dousa",
        arti: "GERAKAN",
      },
      {
        kanji: "片足",
        romaji: "Kataashi",
        arti: "SATU KAKI",
      },
      {
        kanji: "膝を曲げ",
        romaji: "Hiza wo mage",
        arti: "LUTUT DITEKUK",
      },
      {
        kanji: "呼吸",
        romaji: "Kokyuu",
        arti: "PERNAFASAN",
      },
      {
        kanji: "姿勢",
        romaji: "Shisei",
        arti: "POSTUR",
      },
      {
        kanji: "異常事態",
        romaji: "Ijou Jitai",
        arti: "SITUASI TIDAK NORMAL",
      },
      {
        kanji: "発生しました",
        romaji: "Hassei shimashita",
        arti: "MUNCUL",
      },
      {
        kanji: "素早く",
        romaji: "Subayaku",
        arti: "CEPAT CEPAT",
      },
      {
        kanji: "同僚",
        romaji: "Douryou",
        arti: "KOLEGA/PARTNER KERJA",
      },
      {
        kanji: "非常停止ボタン",
        romaji: "Hijou Teishi Botan",
        arti: "TOMBOL BERHENTI DARURAT",
      },
      {
        kanji: "協力します",
        romaji: "Kyouryoku shimasu",
        arti: "BEKERJASAMA",
      },
      {
        kanji: "処置",
        romaji: "Shochi",
        arti: "PERLAKUAN",
      },
      {
        kanji: "勝手な行動しません",
        romaji: "Katte na koudou shimasen",
        arti: "TIDAK MELAKUKAN SENDIRI",
      },
      {
        kanji: "変な臭いがします",
        romaji: "Hen na nioi ga shimasu",
        arti: "BAU ANEH",
      },
      {
        kanji: "ランプが点滅している",
        romaji: "Ranpu ga tenmetsu shiteiru",
        arti: "LAMPU BERKEDIP",
      },
      {
        kanji: "レバーがぐらぐらする",
        romaji: "Rebaa ga guragura suru",
        arti: "TUAS NYA BERGERTAR",
      },
      {
        kanji: "慌てて",
        romaji: "Awatete",
        arti: "PANIK",
      },
      {
        kanji: "二次災害",
        romaji: "Niji Saigai",
        arti: "KECELAKAAN LANJUTAN",
      },
      {
        kanji: "被災者",
        romaji: "Hisaisha",
        arti: "KORBAN",
      },
      {
        kanji: "助けます",
        romaji: "Tasukemasu",
        arti: "MENOLONG",
      },
    ],
  },
  Kaigo: {
    color: "#c07ef0",
    words: [
      { kanji: "介護", romaji: "Kaigo", arti: "Perawatan lansia" },
      { kanji: "利用者", romaji: "Riyōsha", arti: "Pengguna (Lansia)" },
      { kanji: "おじいさん", romaji: "Ojiisan", arti: "Kakek" },
      { kanji: "おばあさん", romaji: "Obāsan", arti: "Nenek" },
      { kanji: "車椅子", romaji: "Kurumaisu", arti: "Kursi roda" },
      { kanji: "杖", romaji: "Tsue", arti: "Tongkat bantu jalan" },
      { kanji: "ベッド", romaji: "Beddo", arti: "Tempat tidur" },
      { kanji: "手すり", romaji: "Tesuri", arti: "Pegangan tangan" },
      { kanji: "介助", romaji: "Kaijo", arti: "Bantuan / Pertolongan" },
      { kanji: "食事", romaji: "Shokuji", arti: "Makan" },
      { kanji: "入浴", romaji: "Nyūyoku", arti: "Mandi" },
      { kanji: "トイレ", romaji: "Toire", arti: "Toilet" },
      { kanji: "排泄", romaji: "Haisetsu", arti: "Buang air" },
      { kanji: "オムツ", romaji: "Omutsu", arti: "Popok" },
      { kanji: "着替え", romaji: "Kigae", arti: "Ganti baju" },
      { kanji: "歩行", romaji: "Hokō", arti: "Berjalan" },
      { kanji: "転倒", romaji: "Tentō", arti: "Jatuh" },
      { kanji: "薬", romaji: "Kusuri", arti: "Obat" },
      { kanji: "水分", romaji: "Suibun", arti: "Minum air" },
      { kanji: "バイタル", romaji: "Baitaru", arti: "Tanda vital" },
      { kanji: "熱", romaji: "Netsu", arti: "Demam / Panas" },
      { kanji: "血圧", romaji: "Ketsuatsu", arti: "Tekanan darah" },
      { kanji: "痛い", romaji: "Itai", arti: "Sakit" },
      { kanji: "苦しい", romaji: "Kurushii", arti: "Sesak / Menderita" },
      { kanji: "大丈夫", romaji: "Daijōbu", arti: "Tidak apa-apa" },
      { kanji: "気持ちいい", romaji: "Kimochi ii", arti: "Merasa nyaman" },
      {
        kanji: "レクリエーション",
        romaji: "Rekuriēshon",
        arti: "Kegiatan hiburan",
      },
      { kanji: "散歩", romaji: "Sanpo", arti: "Jalan-jalan" },
      { kanji: "挨拶", romaji: "Aisatsu", arti: "Salam / Sapaan" },
      { kanji: "名前", romaji: "Namae", arti: "Nama" },
      { kanji: "呼ぶ", romaji: "Yobu", arti: "Memanggil" },
      { kanji: "聞く", romaji: "Kiku", arti: "Mendengar / Bertanya" },
      { kanji: "話す", romaji: "Hanasu", arti: "Berbicara" },
      { kanji: "笑顔", romaji: "Egao", arti: "Senyuman" },
      { kanji: "丁寧", romaji: "Teinei", arti: "Sopan / Ramah" },
      { kanji: "記録", romaji: "Kiroku", arti: "Catatan" },
      { kanji: "報告", romaji: "Hōkoku", arti: "Laporan" },
      { kanji: "相談", romaji: "Sōdan", arti: "Konsultasi" },
      { kanji: "夜勤", romaji: "Yakin", arti: "Shift malam" },
      { kanji: "交代", romaji: "Kōtai", arti: "Ganti shift" },
      { kanji: "介護士", romaji: "Kaigoshi", arti: "Perawat lansia" },
      {
        kanji: "車椅子のブレーキ",
        romaji: "Kurumaisu no burēki",
        arti: "Rem kursi roda",
      },
      { kanji: "おむつ交換", romaji: "Omutsu kōkan", arti: "Ganti popok" },
      {
        kanji: "体位変換",
        romaji: "Taii henkan",
        arti: "Mengubah posisi tubuh",
      },
      { kanji: "移乗", romaji: "Ijō", arti: "Berpindah tempat" },
      { kanji: "誤嚥", romaji: "Goen", arti: "Tersedak / Salah telan" },
      { kanji: "認知症", romaji: "Ninchishō", arti: "Demensia / Pikun" },
      {
        kanji: "デイサービス",
        romaji: "Dei sābisu",
        arti: "Pelayanan penitipan harian",
      },
      { kanji: "施設", romaji: "Shisetsu", arti: "Fasilitas / Panti jompo" },
      { kanji: "訪問介護", romaji: "Hōmon kaigo", arti: "Perawatan di rumah" },
      { kanji: "口腔ケア", romaji: "Kōkū kea", arti: "Perawatan mulut / gigi" },
      { kanji: "入れ歯", romaji: "Ireba", arti: "Gigi palsu" },
      { kanji: "体温計", romaji: "Taionkei", arti: "Termometer" },
      { kanji: "脈拍", romaji: "Myakuhaku", arti: "Denyut nadi" },
      { kanji: "呼吸", romaji: "Kokyū", arti: "Pernapasan" },
      { kanji: "声かけ", romaji: "Koekake", arti: "Menyapa / Mengajak bicara" },
      { kanji: "傾聴", romaji: "Keichō", arti: "Mendengarkan dengan seksama" },
      { kanji: "見守り", romaji: "Mimamori", arti: "Mengawasi / Menjaga" },
      { kanji: "申し送り", romaji: "Mōshiokuri", arti: "Serah terima tugas" },
      {
        kanji: "お疲れ様です",
        romaji: "Otsukaresama desu",
        arti: "Terima kasih atas kerja kerasnya",
      },
    ],
  },
  "Dasar N4": {
    color: "#7eb8f7",
    words: [
      { kanji: "仕事", romaji: "Shigoto", arti: "Pekerjaan" },
      { kanji: "休み", romaji: "Yasumi", arti: "Libur / Istirahat" },
      { kanji: "時間", romaji: "Jikan", arti: "Waktu" },
      { kanji: "遅刻", romaji: "Chikoku", arti: "Terlambat" },
      { kanji: "早退", romaji: "Sōtai", arti: "Pulang cepat" },
      { kanji: "欠勤", romaji: "Kekkin", arti: "Absen / Tidak masuk" },
      { kanji: "連絡", romaji: "Renraku", arti: "Menghubungi" },
      { kanji: "相談", romaji: "Sōdan", arti: "Konsultasi / Diskusi" },
      { kanji: "確認", romaji: "Kakunin", arti: "Cek / Konfirmasi" },
      { kanji: "準備", romaji: "Junbi", arti: "Persiapan" },
      { kanji: "片付け", romaji: "Katazuke", arti: "Membereskan" },
      { kanji: "道具", romaji: "Dōgu", arti: "Alat" },
      { kanji: "場所", romaji: "Basho", arti: "Tempat" },
      { kanji: "使い方", romaji: "Tsukaikata", arti: "Cara pakai" },
      { kanji: "教える", romaji: "Oshieru", arti: "Mengajar / Memberitahu" },
      { kanji: "習う", romaji: "Narau", arti: "Belajar" },
      { kanji: "覚える", romaji: "Oboeru", arti: "Mengingat" },
      { kanji: "忘れる", romaji: "Wasureru", arti: "Lupa" },
      { kanji: "間違える", romaji: "Machigaeru", arti: "Salah" },
      { kanji: "直す", romaji: "Naosu", arti: "Memperbaiki" },
      { kanji: "手伝う", romaji: "Tetsudau", arti: "Membantu" },
      { kanji: "運ぶ", romaji: "Hakobu", arti: "Membawa" },
      { kanji: "急ぐ", romaji: "Isogu", arti: "Buru-buru" },
      { kanji: "頑張る", romaji: "Ganbaru", arti: "Semangat" },
      { kanji: "疲れる", romaji: "Tsukareru", arti: "Lelah" },
      { kanji: "眠い", romaji: "Nemui", arti: "Ngantuk" },
      { kanji: "危ない", romaji: "Abunai", arti: "Bahaya" },
      { kanji: "注意", romaji: "Chūi", arti: "Hati-hati" },
      { kanji: "安全", romaji: "Anzen", arti: "Aman" },
      { kanji: "大事", romaji: "Daiji", arti: "Penting" },
      { kanji: "必要", romaji: "Hitsuyō", arti: "Perlu" },
      { kanji: "理由", romaji: "Riyū", arti: "Alasan" },
      { kanji: "意味", romaji: "Imi", arti: "Arti" },
      { kanji: "説明", romaji: "Setsumei", arti: "Penjelasan" },
      { kanji: "質問", romaji: "Shitsumon", arti: "Pertanyaan" },
      { kanji: "答え", romaji: "Kotae", arti: "Jawaban" },
      { kanji: "給料", romaji: "Kyūryō", arti: "Gaji" },
      { kanji: "住所", romaji: "Jūsho", arti: "Alamat" },
      { kanji: "電話番号", romaji: "Denwa bangō", arti: "Nomor telepon" },
      { kanji: "印鑑", romaji: "Inkan", arti: "Stempel nama" },
      { kanji: "経験", romaji: "Keiken", arti: "Pengalaman" },
      { kanji: "予定", romaji: "Yotei", arti: "Rencana / Jadwal" },
      { kanji: "状況", romaji: "Jōkyō", arti: "Situasi / Keadaan" },
      { kanji: "原因", romaji: "Gen'in", arti: "Penyebab" },
      { kanji: "結果", romaji: "Kekka", arti: "Hasil" },
      { kanji: "解決", romaji: "Kaiketsu", arti: "Solusi / Penyelesaian" },
      { kanji: "責任", romaji: "Sekinin", arti: "Tanggung jawab" },
      { kanji: "成功", romaji: "Seikō", arti: "Sukses / Berhasil" },
      { kanji: "失敗", romaji: "Shippai", arti: "Gagal" },
      { kanji: "努力", romaji: "Doryoku", arti: "Usaha / Kerja keras" },
      { kanji: "目標", romaji: "Mokuhyō", arti: "Target / Tujuan" },
      { kanji: "規則", romaji: "Kisoku", arti: "Peraturan" },
      { kanji: "協力", romaji: "Kyōryoku", arti: "Kerja sama" },
      { kanji: "変更", romaji: "Henkō", arti: "Perubahan" },
      { kanji: "報告書", romaji: "Hōkokusho", arti: "Laporan (Dokumen)" },
      {
        kanji: "記入する",
        romaji: "Kinyū suru",
        arti: "Mengisi (formulir/dokumen)",
      },
      {
        kanji: "提出する",
        romaji: "Teishutsu suru",
        arti: "Mengumpulkan / Menyerahkan",
      },
      { kanji: "判断", romaji: "Handan", arti: "Penilaian / Keputusan" },
      { kanji: "比較", romaji: "Hikaku", arti: "Perbandingan" },
      { kanji: "表現", romaji: "Hyōgen", arti: "Ungkapan / Ekspresi" },
    ],
  },
};
